"""Initial migration

Revision ID: d402817228b9
Revises: 
Create Date: 2026-05-07 12:55:32.766499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd402817228b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stretching_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True, comment='URL gambar panduan gerakan'),
    sa.Column('animation_url', sa.Text(), nullable=True, comment='URL animasi panduan gerakan'),
    sa.Column('default_reps', sa.Integer(), nullable=False, comment='Jumlah repetisi default'),
    sa.Column('default_duration_seconds', sa.Integer(), nullable=False, comment='Durasi default per gerakan (detik)'),
    sa.Column('body_part', sa.String(length=50), nullable=True, comment='Area tubuh target (neck, back, shoulder, etc.)'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bmi_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False, comment='Tinggi badan dalam cm'),
    sa.Column('weight_kg', sa.Float(), nullable=False, comment='Berat badan dalam kg'),
    sa.Column('bmi_value', sa.Float(), nullable=True, comment='Nilai BMI yang dihitung'),
    sa.Column('bmi_category', sa.String(length=20), nullable=True, comment='underweight | normal | overweight | obese'),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu perhitungan BMI terakhir'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('hydration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Float(), nullable=False, comment='Jumlah air dalam ml'),
    sa.Column('log_date', sa.Date(), nullable=False, comment='Tanggal log untuk query harian'),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hydration_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_target_ml', sa.Float(), nullable=False, comment='Target air harian dalam ml (BB × 30)'),
    sa.Column('reminder_interval_minutes', sa.Integer(), nullable=False, comment='Interval pengingat dalam menit'),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_start_time', sa.Time(), nullable=False, comment='Jam mulai pengingat'),
    sa.Column('reminder_end_time', sa.Time(), nullable=False, comment='Jam akhir pengingat'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notulens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True, comment='Hasil transkripsi audio'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Ringkasan AI'),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Action items dari AI'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Durasi rekaman (detik)'),
    sa.Column('audio_url', sa.Text(), nullable=True, comment='URL file audio'),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pomodoro_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='classic | deep_work | extend'),
    sa.Column('focus_duration_minutes', sa.Integer(), nullable=False, comment='Durasi fokus dalam menit'),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False, comment='Durasi istirahat dalam menit'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stretching_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('correct_reps', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Durasi aktual sesi (detik)'),
    sa.Column('accuracy_score', sa.Float(), nullable=True, comment='Skor akurasi 0-100 berdasarkan correct_reps/total_reps'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='completed | cancelled | in_progress'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['stretching_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='important | normal'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | done'),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_date', sa.Date(), nullable=True, comment='Tanggal tugas untuk filter'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pomodoro_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('setting_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='Mode saat sesi berjalan'),
    sa.Column('session_type', sa.String(length=10), nullable=False, comment='focus | break'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Durasi yang di-set (detik)'),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True, comment='Durasi aktual (detik)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='completed | cancelled | in_progress'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False, comment='Tanggal sesi untuk agregasi harian'),
    sa.ForeignKeyConstraint(['setting_id'], ['pomodoro_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stretching_reps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('rep_number', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True, comment="Pesan feedback posisi (e.g., 'Luruskan punggung')"),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['stretching_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stretching_reps')
    op.drop_table('pomodoro_sessions')
    op.drop_table('user_preferences')
    op.drop_table('todos')
    op.drop_table('stretching_sessions')
    op.drop_table('pomodoro_settings')
    op.drop_table('notulens')
    op.drop_table('hydration_settings')
    op.drop_table('hydration_logs')
    op.drop_table('bmi_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stretching_exercises')
    # ### end Alembic commands ###
